### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by hectorluisnavas** [aczekajski/iitc-plugin-mininomaly#3]
When I execute the command in the console, the following error appears.

```
TypeError: plugin.miniNomalyPlugin is undefineddebugger eval code:1:1
    <anonymous> debugger eval code:1
```

**Comment by aczekajski** [comment]
Are you sure you've installed the mininomaly plugin from https://github.com/aczekajski/iitc-plugin-mininomaly/releases (`plugin.user.js` file) in your tampermonkey along with IITC and Bookmarks plugin?

I might've too easily assumed that this step is obvious and didn't include it in the readme 😅

**Comment by hectorluisnavas** [comment]
yes... I have the 2 files installed (plugin.user.js and plugin.meta.js). I tried with a fresh install of IITC (IITCme and IITC CE version) and the plugin no works now; that's weird because 4 month ago the plugin works without problems. I was just going to set it up for an IFS today. 😢
Attach screens.
<img width="1176" alt="Screen Shot 2019-12-07 at 7 56 46 AM" src="https://user-images.githubusercontent.com/6127744/70375039-82308d80-18c7-11ea-87ae-81d8c28d067f.png">
<img width="1017" alt="Screen Shot 2019-12-07 at 8 01 04 AM" src="https://user-images.githubusercontent.com/6127744/70375088-cde33700-18c7-11ea-8106-a5a1659b53cd.png">
<img width="1017" alt="Screen Shot 2019-12-07 at 8 01 26 AM" src="https://user-images.githubusercontent.com/6127744/70375091-d3d91800-18c7-11ea-94f8-a062bdd44811.png">

OS: macOS Catalina 10.15.1
Firefox Developer Edition 72.0b3 and Google Chrome 78.0.3904.108

**Comment by aczekajski** [comment]
You have it installed twice now, disable one of them. But if it doesn't work, I must look into the issue myself which I'll be unable to do today.

**Comment by hectorluisnavas** [comment]
I do it... the first error about execution script is no longer shown to me in the console, the second error continues, when I try to configure the plugin using the console.

Just in case, you can write me on telegram to [http://t.me/RazorEc](http://t.me/RazorEc) so as not to make this thread very long.

Greetings and thank you very much for the help

**Comment by aczekajski** [comment]
Version 2.0.0 just got released, along with many different bugfixes. Check the new version and let me know if the new version works properly.

**Comment by aczekajski** [comment]
I've finally reproduced the bug. Release 2.0.1 resolves it.
